name: CI

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  can-run-ci:
    runs-on: ubuntu-latest
    if: |
      (!github.event.pull_request.head.repo.fork) ||
      (github.event.pull_request.head.repo.fork &&
        github.event.action == 'labeled' &&
        github.event.label.name == 'safe-to-test')
    steps:
      - name: ok
        run: echo "yes"

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: read secret
        run: ./echo.sh
        env:
          DUMP: ${{ secrets.SECRET }}

      - name: echo context
        run: echo '${{ toJSON(github) }}'
